core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('cart-summary/', views.CartSummaryView.as_view(), name='cart-summary'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-product-from-cart/<slug>/', views.remove_a_product_from_cart, name='remove-product-from-cart'),
    path('payment/stripe/', views.PaymentView.as_view(), name='payment'),
    path('payment/paypal/', views.paypal_payment, name='paypal_payment'),
    path('payment/paypal/done', views.paypal_done, name='paypal_done'),
    path('payment/paypal/cancelled', views.paypal_cancelled, name='paypal_cancelled'),
]

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
# Create your models here.

CHOICES_OF_CATEGORY = (
	('S', 'SHIRT'),
	('SW', 'Sport Wear'),
	('OW', 'Outwear')
)

LABELS = (
	('P', 'primary'),
	('S', 'secondary'),
	('D', 'danger')
)


class Product(models.Model):
	"""docstring for Product"""
	title = models.CharField(max_length=100)
	price = models.FloatField()
	price_discount = models.FloatField(blank=True, null=True)
	category = models.CharField(choices=CHOICES_OF_CATEGORY, max_length=2)
	label = models.CharField(choices=LABELS, max_length=2)
	decription = models.TextField()
	image = models.ImageField(blank=True, null=True, upload_to="images_uploads/")
	slug = models.SlugField()

	def __str__(self):
		return self.title

	def get_add_to_cart_url(self):
		return reverse("core:add-to-cart", kwargs={
			'slug': self.slug
			})

	def get_remove_from_cart_url(self):
		return reverse("core:remove-from-cart", kwargs={
			'slug': self.slug
			})

	def get_absolute_url(self):
		return reverse("core:product", kwargs={
			'slug': self.slug
		})


class OrderItem(models.Model):
	"""docstring for OrderItem"""
	user = models.ForeignKey(settings.AUTH_USER_MODEL, 
							 on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	ordered = models.BooleanField(default=False)
	num_of_prod = models.IntegerField(default=1)

	def __str__(self):
		return f"{self.num_of_prod} of {self.product.title}"

	def get_total_price_of_product(self):
		return self.num_of_prod * self.product.price

	def get_total_discount_price_of_product(self):
		return self.num_of_prod * self.product.price_discount

	def get_absolute_price(self):
		if self.product.price_discount:
			return self.get_total_discount_price_of_product()
		return self.get_total_price_of_product()


class Order(models.Model):
	"""docstring for Order"""
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	products = models.ManyToManyField(OrderItem)
	start_date = models.DateTimeField(auto_now_add=True)
	ordered_date = models.DateTimeField()
	ordered = models.BooleanField(default=False)
	bill_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, 
									 blank=True, null=True)
	payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, 
								blank=True, null=True)

	
	def __str__(self):
		return self.user.username

	def get_total(self):
		total = 0
		for product_order in self.products.all():
			total += product_order.get_absolute_price()
		return total


class BillingAddress(models.Model):

	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	street = models.CharField(max_length=100)
	country = CountryField(multiple=False)
	apartment = models.CharField(max_length=100)
	zip_code = models.CharField(max_length=100)

	def __str__(self):
		return self.user.username
		
		
class Payment(models.Model):
	stripe_charge_id = models.CharField(max_length=50)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, 
							 on_delete=models.SET_NULL,
							 blank=True, null=True)
	amount = models.FloatField()
	timestamp =  models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.username

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
     <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

  {% include "navbar.html" %}

  

<body>
  <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
         
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
    {% endif %}
  </div>

    {% block content  %}
    {% endblock content %}

  {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/cart_summary.html
  <!--/.Carousel Wrapper-->
{% extends "base.html" %}

{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">

      <div class="table-responsive text-nowrap">
        <h2>Your Product Cart</h2>
        <table class="table">
          <thead>
            <tr>
               <th scope="col">#</th>
              <th scope="col">Product</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
              <th scope="col">Products Total Price</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for product_order in order.products.all %}
                 <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ product_order.product.title }}</td>
              <td>{{ product_order.product.price }}</td>
              <td>
                <a href="{% url 'core:remove-product-from-cart' product_order.product.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ product_order.num_of_prod }}
                <a href="{% url 'core:add-to-cart' product_order.product.slug %}"><i class="fas fa-plus ml-2"></i></a>
              </td>
              <td>
                {% if product_order.product.price_discount %}
                  ${{ product_order.get_total_discount_price_of_product }}
                {% else %}
                   ${{ product_order.get_total_price_of_product }}
                {% endif %}

              </td>
              <td>
                <a href="{% url 'core:remove-from-cart' product_order.product.slug %}">
                <i class="far fa-trash-alt"></i>
              </a>
              </td>
            </tr>
            {% empty %}
            <tr>
              <td colspan="4">Your cart is empty</td>
            </tr>
              <tr>
              <td colspan="5">
                <a class="btn btn-primary float-right" href="/">Continue Shopping</a>  
              </td>
            </tr>
            {% endfor %}
            {% if order.get_total %}
                
            <tr>
              <td colspan="4"><b>Total Order Price</b></td>
              <td><b>${{ order.get_total }}</b></td>
            </tr>
            <tr>
              <td colspan="5">
                <a class="btn btn-warning float-right ml-2" href="/checkout/">Proceed to checkout</a>
                <a class="btn btn-primary float-right" href="/">Continue Shopping</a>
                
              </td>
            </tr>
            {% endif %}
            
          </tbody>
        </table>

      </div>

    </div>
  </main>
  <!--Main layout-->


{% endblock %}

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


  <!--Main layout-->
  <main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class="card-body">
              {% csrf_token %}
              <!--address-->
              <div class="md-form mb-5">
                <!--<input type="text" id="address" class="form-control" placeholder="1234 Main St">-->
                {{ form.street }}
                <label for="address" class="">Address</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                <!--<input type="text" id="address-2" class="form-control" placeholder="Apartment or suite">-->
                {{ form.apartment }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  <!--<select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>United States</option>
                  </select>-->
                  {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  <!--<input type="text" class="form-control" id="zip" placeholder="" required>-->
                  {{ form.zip_code }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
          <input {% if form.same_billing_address.value %}
                    checked 
                {% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
            
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
              <input {% if form.save_information.value %}
                    checked 
                {% endif %} type="checkbox" class="custom-control-input" name="save_information" id="save-info">
            
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
              {% for val, text in form.fields.payment.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ text }}" name="payment" value="{{ val }}" type="radio" class="custom-control-input" required>
    <label class="custom-control-label" for="{{ text }}">{{ text }}</label>
                </div>
                <!--
                <div class="custom-control custom-radio">
                  <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="debit">Debit card</label>
                </div>-->
                <!--<div class="custom-control custom-radio">
                  <input id="{{ text }}" name="{{ text }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ text }}">{{ val }}</label>
                </div>-->
                {% endfor %}
              </div>
                
               
              <!--
              <div class="row">
                <div class="col-md-6 mb-3">
                  <label for="cc-name">Name on card</label>
                  <input type="text" class="form-control" id="cc-name" placeholder="" required>
                  <small class="text-muted">Full name as displayed on card</small>
                  <div class="invalid-feedback">
                    Name on card is required
                  </div>
                </div>
                <div class="col-md-6 mb-3">
                  <label for="cc-number">Credit card number</label>
                  <input type="text" class="form-control" id="cc-number" placeholder="" required>
                  <div class="invalid-feedback">
                    Credit card number is required
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3 mb-3">
                  <label for="cc-expiration">Expiration</label>
                  <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
                  <div class="invalid-feedback">
                    Expiration date required
                  </div>
                </div>
                <div class="col-md-3 mb-3">
                  <label for="cc-expiration">CVV</label>
                  <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
                  <div class="invalid-feedback">
                    Security code required
                  </div>
                </div>
              </div>
            -->
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock %}

templates/footer.html
  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--<hr class="my-4">-->

    <!--Call to action-->
   <!-- <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank"
        role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start
        free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>-->
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/home.html
  <!--/.Carousel Wrapper-->
{% extends "base.html" %}

{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
        {% for item in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                  alt=""> -->
                  {% if item.image %}
                  <img src="{{ item.image.url }}" class="card-img-top"
                  alt="">
                  {% endif %}
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{item.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                    {% if item.price_discount %}
                    {{ item.price_discount }}
                    {% else %}
                  {{ item.price }}
                  {% endif  %}
                </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}


        </div>
        <!--Grid row-->


      </section>
      <!--Section: Products v.3-->

      {% if is_paginated %}
      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
          {% if page_obj.has_previous %}
              <!--Arrow left-->
          <li class="page-item">
            <a class="page-link" 
      href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          
          {% endif %}
          

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
      

          {% if page_obj.has_next %}
              <li class="page-item">
            <a class="page-link" 
          href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
          
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}

    </div>
  </main>
  <!--Main layout-->


{% endblock %}

templates/navbar.html
{% load cart_tags %}
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'core:home' %}" target="_blank">
        <strong class="blue-text">Onine Store</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <!--<li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url "core:home" %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>-->
          <!-- <li class="nav-item">
            <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">About MDB</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
              target="_blank">Free download</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="https://mdbootstrap.com/education/bootstrap/" target="_blank">Free
              tutorials</a>
          </li> -->
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:cart-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> 
                {{request.user|item_in_cart_count }}
              </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
           <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout</span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup</span>
            </a>
          </li>
         {% endif %}
          <!--<li class="nav-item">
            <a href="https://github.com/mdbootstrap/bootstrap-material-design" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              <i class="fab fa-github mr-2"></i>MDB GitHub
            </a>
          </li>-->
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

templates/product.html
{% extends "base.html" %}

{% block content %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt=""> -->
          {% if item.image %}
          <img src="{{ object.image.url }}" class="img-fluid" alt="">
          {% endif %}
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
<!--              <a href="">-->
<!--                <span class="badge blue mr-1">New</span>-->
<!--              </a>-->
<!--              <a href="">-->
<!--                <span class="badge red mr-1">Bestseller</span>-->
<!--              </a>-->
            </div>

            <p class="lead">
           
               {% if object.price_discount %}
                   
                    <span class="mr-1">
                      <del>{{ object.price }}</del>
                    </span>
                     <span>{{ object.price_discount }}</span>
                    {% else %}
                  <span>{{ object.price }}</span>
                  {% endif  %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            <!-- <form class="d-flex justify-content-left">
              
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form>-->
            <a href="{{ object.get_add_to_cart_url }}"
            class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}"
            class="btn btn-danger btn-md my-0 p">
              Remove from cart
              
            </a>
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

 {% endblock %}

templates/product_list.html
{% extends 'base.html' %}

{% block content %}
<h2>here is the list of Products</h2>

{% for item in product %}
    {{ item }}
{% endfor %}
{% endblock content %}